#!/usr/bin/env python3
"""Generate the cat-face icon C arrays as LVGL 9 A8 images from 1bpp PNGs.

Reads the dithered (Bayer) PNGs under ../assets/ and emits two LVGL image
descriptors:
  ../main/cat_icon.c     -> cat_icon    (72x72, from cat_bayer_72.png)
  ../main/cat_icon_48.c  -> cat_icon_48 (48x48, from cat_bayer_48.png)

The source PNGs are 1bpp: black pixel = ink, white pixel = paper. Each becomes
an A8 image where black is opaque (alpha 255) and white is transparent
(alpha 0). The A8 image carries no color; ui.cpp recolors it black at render
time, so it shows as black dots on the mono reflective panel.
"""
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))


def emit(png_name, symbol, out_name):
    src = os.path.join(HERE, "..", "assets", png_name)
    out = os.path.join(HERE, "..", "main", out_name)

    im = Image.open(src).convert("L")
    w, h = im.size
    pixels = im.get_flattened_data() if hasattr(im, "get_flattened_data") else im.getdata()
    px = list(pixels)

    # black (0) -> opaque ink (255 alpha); anything else -> transparent (0).
    alpha = [255 if v < 128 else 0 for v in px]

    lines = []
    lines.append("// Generated by tools/make_icon.py. Do not edit by hand.")
    lines.append('#include "lvgl.h"')
    lines.append("")
    lines.append("static const uint8_t %s_map[%d] = {" % (symbol, w * h))
    for y in range(h):
        chunk = alpha[y * w:(y + 1) * w]
        lines.append("    " + ", ".join("0x%02X" % v for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("const lv_image_dsc_t %s = {" % symbol)
    lines.append("    .header = {")
    lines.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append("        .cf = LV_COLOR_FORMAT_A8,")
    lines.append("        .flags = 0,")
    lines.append("        .w = %d," % w)
    lines.append("        .h = %d," % h)
    lines.append("        .stride = %d," % w)
    lines.append("    },")
    lines.append("    .data_size = %d," % (w * h))
    lines.append("    .data = %s_map," % symbol)
    lines.append("};")
    lines.append("")

    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.normpath(out), "(%dx%d)" % (w, h))


def main():
    emit("cat_bayer_72.png", "cat_icon", "cat_icon.c")
    emit("cat_bayer_48.png", "cat_icon_48", "cat_icon_48.c")


if __name__ == "__main__":
    main()
